name: your-project-name
version: 1.0.0
description: Your project description
main: index.js
scripts:
  start: node index.js
  test: echo "Error: no test specified" && exit 1
author: Your Name
license: MIT
dependencies:
  express: ^4.17.1
  body-parser: ^1.19.0
# Add other dependencies here
devDependencies:
  nodemon: ^2.0.12
  mocha: ^9.1.3
  chai: ^5.3.0
# Add other development dependencies here
